---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ default "wireguard" .Values.metadata.name }} 
  namespace: {{ default "vpn" .Values.metadata.namespace }} 
spec:
  selector:
    matchLabels:
      name: {{ default "wireguard" .Values.metadata.name }}
  template:
    metadata:
      labels:
        name: {{ default "wireguard" .Values.metadata.name }}
    spec:
      containers:
        - name: {{ default "wireguard" .Values.metadata.name }}
          image: lscr.io/linuxserver/wireguard:latest
          ports:
            - containerPort: 51820
              name: {{ default "wireguard" .Values.metadata.name }}
              protocol: UDP
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sysctl -w net.ipv4.conf.all.src_valid_mark=1" ]
          env:
            - name: "TZ"
              value: {{ default "Europe/Oslo" .Values.spec.timezone }}
            # Keep the PEERS environment variable to force server mode
            - name: "PEERS"
              value: "Peer"
          volumeMounts:
            - name: wireguard-config
              mountPath: /config
            - name: wireguard-modules
              mountPath: /lib/modules
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
      volumes:
        - name: wireguard-config
          persistentVolumeClaim:
            claimName: pvc-{{ .Values.metadata.name }}
        - name: wireguard-modules
          emptyDir: {}
      imagePullSecrets:
        - name: docker-registry
