apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfsshare/wireguard/config
    server: 192.168.0.120
