apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
