apiVersion: v1
kind: Service
metadata:
  name: wireguard 
  namespace: {{ .Values.metadata.namespace }} 
spec:
  type: {{ .Values.service.type }}
  selector:
    name: wireguard
  ports:
  - name: wireguard
    nodePort: {{ .Values.service.nodePort }}
    port: 51820
    protocol: UDP
    targetPort: 51820 
