apiVersion: v1
kind: Service
metadata:
  name: {{ default "wireguard" .Values.metadata.name }} 
  namespace: {{ default "vpn" .Values.metadata.namespace }} 
spec:
  type: {{ default "NodePort" .Values.service.type }}
  selector:
    name: {{ default "wireguard" .Values.metadata.name }} 
  ports:
  - name: {{ default "wireguard" .Values.metadata.name }} 
    nodePort: {{ default "31313" .Values.service.nodePort }}
    port: 51820
    protocol: UDP
    targetPort: 51820 
